### ISSUE TITLE
Not Tested up to WordPress 5.2

### ISSUE THREAD

**Issue by BFTrick** [woocommerce/storefront-product-sharing#10]
Hey Woo peeps!

Would you mind testing against the latest version of WordPress & WooCommerce so the plugin repo doesn't show this warning?

![Storefront_Product_Sharing_–_WordPress_plugin___WordPress_org](https://user-images.githubusercontent.com/1065372/57792815-2620d480-76fd-11e9-9773-71a558a02b72.jpg)

**Comment by tiagonoronha** [comment]
Done! Thanks :)
