### ISSUE TITLE
Selecting Twitter icon opens new tweet with no content

### ISSUE THREAD

**Issue by senff** [woocommerce/storefront-product-sharing#15]
## Describe the bug
When selecting the Twitter icon on a product page, it opens a new tweet modal, but without any content.

Isolating the problem (mark completed items with an [x]):
- [x] I have deactivated other plugins and themes and confirmed this bug occurs when only WooCommerce + Storefront + this extension are active.
- [x] I can reproduce this bug consistently using the steps below.

## To Reproduce
1. Go to any product page that has the sharing icons
2. Click on the Twitter icon (pointing to https://twitter.com/intent/tweet?status=Sitename%20%233+https://mywoocommercesite.com/product/something/ )
3. See new tweet modal with no content

## Screenshots
https://cdn-std.droplr.net/files/acc_646767/Yx7NP3

## Expected behavior
The tweet should be prefilled with the URL to the product.

### Browser Environment
Any platform, any browser.

### WordPress Environment
WordPress 5.4.2, WooCommerce 4.3.2 and Storefront 2.5.8.

**Comment by billrobbins** [comment]
We had a customer back asking about when this will be released.  Any idea of when an update will come out?

**Comment by ldr2273** [comment]
4035567-zen

Hi @jconroy -

Any ETA or idea of when this will be released? TIA!
