### ISSUE TITLE
Twitter sharing opens blank compose window on Twitter (without the product page link)

### ISSUE THREAD

**Issue by anant1811** [woocommerce/storefront-product-sharing#23]
## Describe the bug

Twitter sharing button opens only blank tweet compose window. Ideally, it should include the link of the product page in the window when it is opened:

![https://d.pr/i/TOsQTn](https://d.pr/i/TOsQTn+) 
Full Size: https://d.pr/i/TOsQTn

Isolating the problem (mark completed items with an [x]):
- [x] I have deactivated other plugins and themes and confirmed this bug occurs when only WooCommerce + Storefront + this extension are active.
- [x] I can reproduce this bug consistently using the steps below.

### Browser Environment
Please provide as much detail as possible about your testing environment.

- Platform: e.g. macOS, Windows, iOS
- Browser(s):

### WordPress Environment
Please provide relevant details of your WordPress setup and server environment.

<details>
```
Copy and paste the system status report from WooCommerce > System Status in WordPress admin.
```
</details>

**Comment by findingsimple** [comment]
[I think this has been fixed](https://github.com/woocommerce/storefront-product-sharing/issues/15), we're just _slow_ on release
