### ISSUE TITLE
Open social share links in a new tab.

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/storefront-product-sharing#4]
These links should really open in a new tab: https://github.com/woocommerce/storefront-product-sharing/blob/master/storefront-product-sharing.php#L218-L221. It takes the user away from the website, and after posting, keeps them on the social media site.

Happy to submit a PR if this a change you agree with. CC @jameskoster

**Comment by jameskoster** [comment]
Yes please mate

**Comment by WPprodigy** [comment]
Hmm, don't have access to push a branch here it seems. Guess I'll fork it first
