### ISSUE TITLE
Icons don't work with Storefront 2.3

### ISSUE THREAD

**Issue by melindahelt** [woocommerce/storefront-product-sharing#7]
Ticket: zd-1148648

Issue:
Links appear, but icons do not when using this plugin with Storefront 2.3 and WooCommerce 3.3.5. User reported problem, I was able to replicate issue.

![](http://cld.wthms.co/dLv9uv+)Image Link: http://cld.wthms.co/dLv9uv

**Comment by jobthomas** [comment]
Another one reported here https://wordpress.org/support/topic/icons-disappeared-after-update/

**Comment by mdmoore** [comment]
More reports of this here:  https://wordpress.org/support/topic/new-storefront-version-is-incompatible-with-the-current-plugin-version/

**Comment by rynaldos-zz** [comment]
Another one here https://woothemes.zendesk.com/agent/tickets/1172013

**Comment by mdmoore** [comment]
More reports today.  @tiagonoronha Any ETA on this?  Thanks :)

**Comment by madeincosmos** [comment]
Looks like Font Awesome is missing in Storefront 2.3.1. Just got another user with the same problem.

**Comment by amandasjackson** [comment]
1192326-zen also reported this issue via HC

**Comment by kaiserguy** [comment]
Any ETA? Having the same issue on JetFanUSA.com product pages.

**Comment by kaiserguy** [comment]
Adding this CSS code to my site fixes the email icon
`.storefront-product-sharing ul li a:before {
	font-family: "Font Awesome 5 Free";
}`

**Comment by kaiserguy** [comment]
Requesting an embed code from https://fontawesome.com/v4.7.0/get-started/ and placing the embed code on my site fixed the whole issue without any changes to the CSS
